/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {


  worldBar: [
    {
      type: 'autogenerated',
      dirName: 'World', // Generate sidebar slice 
    }],
    charBar: [
    {
      type: 'autogenerated',
      dirName: 'Characters', // Generate sidebar slice
    }],
    campBar: [
    {
      type: 'autogenerated',
      dirName: 'Campaigns', // Generate sidebar slice 
    }],
    artBar:[
    {
      type: 'autogenerated',
      dirName: 'Artifacts', // Generate sidebar slice
    }],
    ruleBar:[
    {
      type: 'autogenerated',
      dirName: 'Rules', // Generate sidebar slice 
    }],  


};

module.exports = sidebars;
